cp ~/IdeaProjects/FactionsX-Parent/FactionsX/build/libs/FactionsX-Core-1.0.6-RC.jar ~/Servers/server16/plugins/FactionsX-1.0.jar
cp ~/IdeaProjects/FactionsX-Parent/FGrace-Addon/build/libs/FGrace-Addon-1.0.6-RC.jar ~/Servers/server16/plugins/FactionsX/addons/FGrace.jar
#cp ~/IdeaProjects/FactionsX-Parent/FPrinter-Addon/build/libs/FPrinter-Addon-1.0.6-RC.jar ~/Servers/server16/plugins/FactionsX/addons/FPrinter.jar
cp ~/IdeaProjects/FactionsX-Parent/FTOP-Addon/build/libs/FTOP-Addon-1.0.6-RC.jar ~/Servers/server16/plugins/FactionsX/addons/FTOP.jar
cp ~/IdeaProjects/FactionsX-Parent/FTNT-Addon/build/libs/FTNT-Addon-1.0.6-RC.jar ~/Servers/server16/plugins/FactionsX/addons/FTNT.jar
cp ~/IdeaProjects/FactionsX-Parent/FWild-Addon/build/libs/FWild-Addon-1.0.6-RC.jar ~/Servers/server16/plugins/FactionsX/addons/FWild.jar
cp ~/IdeaProjects/FactionsX-Parent/FChest-Addon/build/libs/FChest-Addon-1.0.6-RC.jar ~/Servers/server16/plugins/FactionsX/addons/FChest.jar
cp ~/IdeaProjects/FactionsX-Parent/FRoster-Addon/build/libs/FRoster-Addon-1.0.6-RC.jar ~/Servers/server16/plugins/FactionsX/addons/FRoster.jar
cp ~/IdeaProjects/FactionsX-Parent/FDynmap-Addon/build/libs/FDynmap-Addon-1.0.6-RC.jar ~/Servers/server16/plugins/FactionsX/addons/FDynmap.jar
cp ~/IdeaProjects/FactionsX-Parent/FCropUpgrades-Addon/build/libs/FCropUpgrades-Addon-1.0.6-RC.jar ~/Servers/server16/plugins/FactionsX/addons/FCropUpgrades.jar